/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "stdio.h"
#include "arm_math.h"
#include <errno.h>
#include <sys/unistd.h>
#include <string.h>
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
typedef struct {
  float32_t magnitude;
  uint16_t bin_index;
} FrequencyPeak;
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
#define TAG_TOP_TEN_FREQ
//#define TAG_FFT_ALL
#define FIR_ENABLE 
#define FIR_C1    //600HZ_600HZ
// #define FIR_C2
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
I2C_HandleTypeDef hi2c1;

I2S_HandleTypeDef hi2s2;
DMA_HandleTypeDef hdma_spi2_rx;

UART_HandleTypeDef huart2;
DMA_HandleTypeDef hdma_usart2_tx;

/* USER CODE BEGIN PV */
// Generated by FIRfilterCoeff.py
#ifdef FIR_C1
static const float32_t h[] = {
  0.000000000000000000,
  0.000000007212970196,
  0.000000055131376202,
  0.000000171543973319,
  0.000000360266179641,
  0.000000594874965645,
  0.000000818935100534,
  0.000000953269382216,
  0.000000909594621891,
  0.000000608652866177,
  0.000000000000000000,
  -0.000000919966594950,
  -0.000002095239515927,
  -0.000003405721984287,
  -0.000004673080368682,
  -0.000005677570045858,
  -0.000006184832442803,
  -0.000005979993496011,
  -0.000004904940557073,
  -0.000002893643362343,
  0.000000000000000000,
  0.000003586954564869,
  0.000007544518199528,
  0.000011436700949649,
  0.000014753424308920,
  0.000016965877505996,
  0.000017592859001211,
  0.000016270823733091,
  0.000012818966330517,
  0.000007290250698265,
  0.000000000000000000,
  -0.000008474487081748,
  -0.000017326945232164,
  -0.000025587771714763,
  -0.000032218218776113,
  -0.000036225105432006,
  -0.000036784580473335,
  -0.000033361080813736,
  -0.000025806670682806,
  -0.000014426673819225,
  0.000000000000000000,
  0.000016253307473552,
  0.000032759348072180,
  0.000047728294350815,
  0.000059332463244602,
  0.000065908274776839,
  0.000066161433362343,
  0.000059352221390768,
  0.000045437779669613,
  0.000025150889032437,
  0.000000000000000000,
  -0.000027817282490325,
  -0.000055586016677138,
  -0.000080320078295768,
  -0.000099062317925644,
  -0.000109210464970957,
  -0.000108835063599250,
  -0.000096953558356075,
  -0.000073726294863681,
  -0.000040545803575662,
  0.000000000000000000,
  0.000044297862088247,
  0.000088005618738364,
  0.000126453688554378,
  0.000155117004147216,
  0.000170112150069698,
  0.000168667957176161,
  0.000149516417017767,
  0.000113155084000910,
  0.000061942104130263,
  0.000000000000000000,
  -0.000067076894279026,
  -0.000132695671015413,
  -0.000189882385686299,
  -0.000231989162332351,
  -0.000253422288578318,
  -0.000250315215958849,
  -0.000221070501681524,
  -0.000166703023080355,
  -0.000090932969583583,
  0.000000000000000002,
  0.000097802431277576,
  0.000192843853678290,
  0.000275067150224225,
  0.000335010294897236,
  0.000364839539779732,
  0.000359285831423614,
  0.000316378861817415,
  0.000237887184878823,
  0.000129397538541096,
  -0.000000000000000001,
  -0.000138415101386375,
  -0.000272201267600355,
  -0.000387254569662938,
  -0.000470448117348628,
  -0.000511061152705928,
  -0.000502052891807850,
  -0.000441037686168213,
  -0.000330840034755072,
  -0.000179544124270732,
  -0.000000000000000001,
  0.000191197111310521,
  0.000375181679884137,
  0.000532622270421465,
  0.000645688551479070,
  0.000699986632638702,
  0.000686259697749221,
  0.000601662834962097,
  0.000450453578221149,
  0.000243990800850278,
  -0.000000000000000001,
  -0.000258863304937024,
  -0.000507045571120453,
  -0.000718548030718960,
  -0.000869571730898905,
  -0.000941092889797799,
  -0.000921098533359573,
  -0.000806231821842976,
  -0.000602643025664755,
  -0.000325912472320292,
  0.000000000000000005,
  0.000344726630027055,
  0.000674233901600613,
  0.000954096882085209,
  0.001152999094859438,
  0.001246110935454701,
  0.001217992860294628,
  0.001064698903326004,
  0.000794820441674298,
  0.000429304787869723,
  -0.000000000000000002,
  -0.000452994581337506,
  -0.000884965733328157,
  -0.001250892939594858,
  -0.001510019745070193,
  -0.001630236735517778,
  -0.001591818175668851,
  -0.001390096195848735,
  -0.001036743084526973,
  -0.000559457156823075,
  0.000000000000000002,
  0.000589301542319519,
  0.001150312757800108,
  0.001624689213087111,
  0.001959789720876354,
  0.002114318999981656,
  0.002063112326118575,
  0.001800531613135314,
  0.001342056394597545,
  0.000723815326136190,
  -0.000000000000000002,
  -0.000761685197981068,
  -0.001486176499962443,
  -0.002098266020155372,
  -0.002530202581153647,
  -0.002728928710850529,
  -0.002662203518427453,
  -0.002322936080422007,
  -0.001731200837943418,
  -0.000933613992632222,
  0.000000000000000003,
  0.000982453153805861,
  0.001917088352576017,
  0.002707032545101008,
  0.003264946690258434,
  0.003522317420895075,
  0.003437333674165345,
  0.003000485639801629,
  0.002237208486919608,
  0.001207155299613224,
  -0.000000000000000003,
  -0.001271987190106345,
  -0.002484014837181999,
  -0.003510625699427079,
  -0.004238241037973694,
  -0.004577178800465129,
  -0.004471921470477553,
  -0.003908521035305639,
  -0.002918255751523590,
  -0.001576979286270625,
  0.000000000000000003,
  0.001667239028090979,
  0.003261980916958090,
  0.004619398068116593,
  0.005588884876617332,
  0.006049853241498540,
  0.005925451898612821,
  0.005192750476131914,
  0.003888196699748424,
  0.002107551518475262,
  -0.000000000000000003,
  -0.002243317149682280,
  -0.004405555526599354,
  -0.006263903857625761,
  -0.007611103046085754,
  -0.008276782191560651,
  -0.008146556730446801,
  -0.007176933645328500,
  -0.005404357235659036,
  -0.002947187833007922,
  0.000000000000000004,
  0.003179732946637637,
  0.006291793906866203,
  0.009018771864230179,
  0.011054991640217888,
  0.012136394457447883,
  0.012068726678476440,
  0.010751408594882765,
  0.008194705559681586,
  0.004528296880536618,
  -0.000000000000000004,
  -0.005035793231986729,
  -0.010139540705696639,
  -0.014816539248567458,
  -0.018553394632726941,
  -0.020858249767653356,
  -0.021301620769129285,
  -0.019554516962313487,
  -0.015420623526151691,
  -0.008859703100028354,
  0.000000000000000004,
  0.010861739710608147,
  0.023273053069527715,
  0.036650747278610257,
  0.050316490520345286,
  0.063540524245060986,
  0.075590318641641716,
  0.085780545680485903,
  0.093520585884290894,
  0.098355932108839944,
  0.100000296625720797,
  0.098355932108839944,
  0.093520585884290894,
  0.085780545680485903,
  0.075590318641641716,
  0.063540524245060986,
  0.050316490520345286,
  0.036650747278610257,
  0.023273053069527715,
  0.010861739710608147,
  0.000000000000000004,
  -0.008859703100028354,
  -0.015420623526151695,
  -0.019554516962313490,
  -0.021301620769129288,
  -0.020858249767653360,
  -0.018553394632726941,
  -0.014816539248567458,
  -0.010139540705696639,
  -0.005035793231986729,
  -0.000000000000000004,
  0.004528296880536617,
  0.008194705559681586,
  0.010751408594882765,
  0.012068726678476440,
  0.012136394457447883,
  0.011054991640217889,
  0.009018771864230181,
  0.006291793906866203,
  0.003179732946637638,
  0.000000000000000004,
  -0.002947187833007923,
  -0.005404357235659036,
  -0.007176933645328501,
  -0.008146556730446803,
  -0.008276782191560651,
  -0.007611103046085756,
  -0.006263903857625761,
  -0.004405555526599355,
  -0.002243317149682280,
  -0.000000000000000003,
  0.002107551518475262,
  0.003888196699748423,
  0.005192750476131913,
  0.005925451898612821,
  0.006049853241498540,
  0.005588884876617333,
  0.004619398068116595,
  0.003261980916958091,
  0.001667239028090979,
  0.000000000000000003,
  -0.001576979286270625,
  -0.002918255751523591,
  -0.003908521035305638,
  -0.004471921470477553,
  -0.004577178800465129,
  -0.004238241037973695,
  -0.003510625699427079,
  -0.002484014837181999,
  -0.001271987190106345,
  -0.000000000000000003,
  0.001207155299613225,
  0.002237208486919609,
  0.003000485639801630,
  0.003437333674165345,
  0.003522317420895077,
  0.003264946690258435,
  0.002707032545101009,
  0.001917088352576017,
  0.000982453153805861,
  0.000000000000000003,
  -0.000933613992632222,
  -0.001731200837943419,
  -0.002322936080422007,
  -0.002662203518427453,
  -0.002728928710850530,
  -0.002530202581153646,
  -0.002098266020155372,
  -0.001486176499962443,
  -0.000761685197981068,
  -0.000000000000000002,
  0.000723815326136190,
  0.001342056394597546,
  0.001800531613135315,
  0.002063112326118576,
  0.002114318999981655,
  0.001959789720876355,
  0.001624689213087111,
  0.001150312757800108,
  0.000589301542319519,
  0.000000000000000002,
  -0.000559457156823076,
  -0.001036743084526974,
  -0.001390096195848735,
  -0.001591818175668851,
  -0.001630236735517778,
  -0.001510019745070193,
  -0.001250892939594858,
  -0.000884965733328158,
  -0.000452994581337506,
  -0.000000000000000002,
  0.000429304787869723,
  0.000794820441674298,
  0.001064698903326005,
  0.001217992860294628,
  0.001246110935454702,
  0.001152999094859438,
  0.000954096882085209,
  0.000674233901600614,
  0.000344726630027055,
  0.000000000000000005,
  -0.000325912472320292,
  -0.000602643025664756,
  -0.000806231821842975,
  -0.000921098533359573,
  -0.000941092889797799,
  -0.000869571730898905,
  -0.000718548030718960,
  -0.000507045571120453,
  -0.000258863304937024,
  -0.000000000000000001,
  0.000243990800850278,
  0.000450453578221150,
  0.000601662834962097,
  0.000686259697749221,
  0.000699986632638703,
  0.000645688551479069,
  0.000532622270421465,
  0.000375181679884137,
  0.000191197111310521,
  -0.000000000000000001,
  -0.000179544124270732,
  -0.000330840034755072,
  -0.000441037686168212,
  -0.000502052891807850,
  -0.000511061152705928,
  -0.000470448117348628,
  -0.000387254569662938,
  -0.000272201267600355,
  -0.000138415101386375,
  -0.000000000000000001,
  0.000129397538541096,
  0.000237887184878823,
  0.000316378861817415,
  0.000359285831423614,
  0.000364839539779732,
  0.000335010294897236,
  0.000275067150224226,
  0.000192843853678290,
  0.000097802431277576,
  0.000000000000000002,
  -0.000090932969583583,
  -0.000166703023080356,
  -0.000221070501681525,
  -0.000250315215958849,
  -0.000253422288578318,
  -0.000231989162332351,
  -0.000189882385686299,
  -0.000132695671015413,
  -0.000067076894279026,
  0.000000000000000000,
  0.000061942104130263,
  0.000113155084000910,
  0.000149516417017767,
  0.000168667957176162,
  0.000170112150069698,
  0.000155117004147216,
  0.000126453688554378,
  0.000088005618738364,
  0.000044297862088247,
  0.000000000000000000,
  -0.000040545803575662,
  -0.000073726294863681,
  -0.000096953558356075,
  -0.000108835063599250,
  -0.000109210464970957,
  -0.000099062317925644,
  -0.000080320078295768,
  -0.000055586016677139,
  -0.000027817282490325,
  0.000000000000000000,
  0.000025150889032437,
  0.000045437779669613,
  0.000059352221390768,
  0.000066161433362343,
  0.000065908274776839,
  0.000059332463244602,
  0.000047728294350815,
  0.000032759348072180,
  0.000016253307473552,
  0.000000000000000000,
  -0.000014426673819225,
  -0.000025806670682806,
  -0.000033361080813736,
  -0.000036784580473335,
  -0.000036225105432006,
  -0.000032218218776113,
  -0.000025587771714763,
  -0.000017326945232164,
  -0.000008474487081748,
  0.000000000000000000,
  0.000007290250698265,
  0.000012818966330517,
  0.000016270823733091,
  0.000017592859001211,
  0.000016965877505996,
  0.000014753424308920,
  0.000011436700949649,
  0.000007544518199528,
  0.000003586954564869,
  0.000000000000000000,
  -0.000002893643362343,
  -0.000004904940557073,
  -0.000005979993496011,
  -0.000006184832442803,
  -0.000005677570045859,
  -0.000004673080368682,
  -0.000003405721984287,
  -0.000002095239515927,
  -0.000000919966594950,
  0.000000000000000000,
  0.000000608652866177,
  0.000000909594621891,
  0.000000953269382216,
  0.000000818935100534,
  0.000000594874965645,
  0.000000360266179641,
  0.000000171543973319,
  0.000000055131376202,
  0.000000007212970196,
  0.000000000000000000,
};
#define FILTER_TAP_NUM 461
#elif defined(FIR_C2)
#define FILTER_TAP_NUM 499
static const float32_t h[] = {0.000026, 
  0.000026, 
  0.000018, 
  0.000004, 
  -0.000013, 
  -0.000029, 
  -0.000038, 
  -0.000036, 
  -0.000023, 
  -0.000002, 
  0.000022, 
  0.000042, 
  0.000052, 
  0.000047, 
  0.000028, 
  -0.000002, 
  -0.000034, 
  -0.000059, 
  -0.000069, 
  -0.000059, 
  -0.000031, 
  0.000009, 
  0.000050, 
  0.000079, 
  0.000088, 
  0.000072, 
  0.000033, 
  -0.000019, 
  -0.000070, 
  -0.000104, 
  -0.000110, 
  -0.000084, 
  -0.000032, 
  0.000034, 
  0.000094, 
  0.000132, 
  0.000134, 
  0.000096, 
  0.000028, 
  -0.000053, 
  -0.000125, 
  -0.000164, 
  -0.000159, 
  -0.000107, 
  -0.000020, 
  0.000079, 
  0.000161, 
  0.000201, 
  0.000185, 
  0.000115, 
  0.000006, 
  -0.000111, 
  -0.000203, 
  -0.000242, 
  -0.000212, 
  -0.000119, 
  0.000014, 
  0.000151, 
  0.000252, 
  0.000286, 
  0.000239, 
  0.000120, 
  -0.000041, 
  -0.000199, 
  -0.000308, 
  -0.000333, 
  -0.000264, 
  -0.000114, 
  0.000077, 
  0.000256, 
  0.000370, 
  0.000383, 
  0.000286, 
  0.000101, 
  -0.000123, 
  -0.000323, 
  -0.000439, 
  -0.000435, 
  -0.000305, 
  -0.000080, 
  0.000180, 
  0.000400, 
  0.000515, 
  0.000488, 
  0.000318, 
  0.000048, 
  -0.000249, 
  -0.000488, 
  -0.000597, 
  -0.000539, 
  -0.000323, 
  -0.000004, 
  0.000331, 
  0.000587, 
  0.000684, 
  0.000589, 
  0.000320, 
  -0.000054, 
  -0.000429, 
  -0.000697, 
  -0.000776, 
  -0.000635, 
  -0.000305, 
  0.000127, 
  0.000542, 
  0.000819, 
  0.000872, 
  0.000676, 
  0.000277, 
  -0.000219, 
  -0.000672, 
  -0.000952, 
  -0.000969, 
  -0.000708, 
  -0.000233, 
  0.000329, 
  0.000820, 
  0.001095, 
  0.001067, 
  0.000730, 
  0.000170, 
  -0.000462, 
  -0.000987, 
  -0.001249, 
  -0.001163, 
  -0.000739, 
  -0.000086, 
  0.000618, 
  0.001173, 
  0.001413, 
  0.001256, 
  0.000732, 
  -0.000023, 
  -0.000801, 
  -0.001380, 
  -0.001585, 
  -0.001342, 
  -0.000705, 
  0.000160, 
  0.001012, 
  0.001607, 
  0.001764, 
  0.001420, 
  0.000655, 
  -0.000328, 
  -0.001255, 
  -0.001857, 
  -0.001949, 
  -0.001485, 
  -0.000577, 
  0.000532, 
  0.001531, 
  0.002129, 
  0.002139, 
  0.001535, 
  0.000467, 
  -0.000776, 
  -0.001845, 
  -0.002425, 
  -0.002331, 
  -0.001564, 
  -0.000318, 
  0.001067, 
  0.002200, 
  0.002746, 
  0.002524, 
  0.001569, 
  0.000125, 
  -0.001411, 
  -0.002603, 
  -0.003094, 
  -0.002716, 
  -0.001543, 
  0.000121, 
  0.001817, 
  0.003059, 
  0.003473, 
  0.002905, 
  0.001479, 
  -0.000430, 
  -0.002296, 
  -0.003578, 
  -0.003886, 
  -0.003089, 
  -0.001370, 
  0.000817, 
  0.002863, 
  0.004174, 
  0.004341, 
  0.003266, 
  0.001202, 
  -0.001300, 
  -0.003541, 
  -0.004865, 
  -0.004848, 
  -0.003433, 
  -0.000962, 
  0.001905, 
  0.004361, 
  0.005679, 
  0.005423, 
  0.003589, 
  0.000624, 
  -0.002674, 
  -0.005372, 
  -0.006662, 
  -0.006094, 
  -0.003731, 
  -0.000155, 
  0.003670, 
  0.006655, 
  0.007887, 
  0.006906, 
  0.003859, 
  -0.000504, 
  -0.005003, 
  -0.008346, 
  -0.009488, 
  -0.007943, 
  -0.003970, 
  0.001459, 
  0.006876, 
  0.010709, 
  0.011717, 
  0.009370, 
  0.004062, 
  -0.002926, 
  -0.009716, 
  -0.014307, 
  -0.015137, 
  -0.011563, 
  -0.004136, 
  0.005425, 
  0.014585, 
  0.020607, 
  0.021281, 
  0.015598, 
  0.004189, 
  -0.010609, 
  -0.025109, 
  -0.034998, 
  -0.036279, 
  -0.026244, 
  -0.004221, 
  0.028070, 
  0.066660, 
  0.105979, 
  0.139876, 
  0.162799, 
  0.170898, 
  0.162799, 
  0.139876, 
  0.105979, 
  0.066660, 
  0.028070, 
  -0.004221, 
  -0.026244, 
  -0.036279, 
  -0.034998, 
  -0.025109, 
  -0.010609, 
  0.004189, 
  0.015598, 
  0.021281, 
  0.020607, 
  0.014585, 
  0.005425, 
  -0.004136, 
  -0.011563, 
  -0.015137, 
  -0.014307, 
  -0.009716, 
  -0.002926, 
  0.004062, 
  0.009370, 
  0.011717, 
  0.010709, 
  0.006876, 
  0.001459, 
  -0.003970, 
  -0.007943, 
  -0.009488, 
  -0.008346, 
  -0.005003, 
  -0.000504, 
  0.003859, 
  0.006906, 
  0.007887, 
  0.006655, 
  0.003670, 
  -0.000155, 
  -0.003731, 
  -0.006094, 
  -0.006662, 
  -0.005372, 
  -0.002674, 
  0.000624, 
  0.003589, 
  0.005423, 
  0.005679, 
  0.004361, 
  0.001905, 
  -0.000962, 
  -0.003433, 
  -0.004848, 
  -0.004865, 
  -0.003541, 
  -0.001300, 
  0.001202, 
  0.003266, 
  0.004341, 
  0.004174, 
  0.002863, 
  0.000817, 
  -0.001370, 
  -0.003089, 
  -0.003886, 
  -0.003578, 
  -0.002296, 
  -0.000430, 
  0.001479, 
  0.002905, 
  0.003473, 
  0.003059, 
  0.001817, 
  0.000121, 
  -0.001543, 
  -0.002716, 
  -0.003094, 
  -0.002603, 
  -0.001411, 
  0.000125, 
  0.001569, 
  0.002524, 
  0.002746, 
  0.002200, 
  0.001067, 
  -0.000318, 
  -0.001564, 
  -0.002331, 
  -0.002425, 
  -0.001845, 
  -0.000776, 
  0.000467, 
  0.001535, 
  0.002139, 
  0.002129, 
  0.001531, 
  0.000532, 
  -0.000577, 
  -0.001485, 
  -0.001949, 
  -0.001857, 
  -0.001255, 
  -0.000328, 
  0.000655, 
  0.001420, 
  0.001764, 
  0.001607, 
  0.001012, 
  0.000160, 
  -0.000705, 
  -0.001342, 
  -0.001585, 
  -0.001380, 
  -0.000801, 
  -0.000023, 
  0.000732, 
  0.001256, 
  0.001413, 
  0.001173, 
  0.000618, 
  -0.000086, 
  -0.000739, 
  -0.001163, 
  -0.001249, 
  -0.000987, 
  -0.000462, 
  0.000170, 
  0.000730, 
  0.001067, 
  0.001095, 
  0.000820, 
  0.000329, 
  -0.000233, 
  -0.000708, 
  -0.000969, 
  -0.000952, 
  -0.000672, 
  -0.000219, 
  0.000277, 
  0.000676, 
  0.000872, 
  0.000819, 
  0.000542, 
  0.000127, 
  -0.000305, 
  -0.000635, 
  -0.000776, 
  -0.000697, 
  -0.000429, 
  -0.000054, 
  0.000320, 
  0.000589, 
  0.000684, 
  0.000587, 
  0.000331, 
  -0.000004, 
  -0.000323, 
  -0.000539, 
  -0.000597, 
  -0.000488, 
  -0.000249, 
  0.000048, 
  0.000318, 
  0.000488, 
  0.000515, 
  0.000400, 
  0.000180, 
  -0.000080, 
  -0.000305, 
  -0.000435, 
  -0.000439, 
  -0.000323, 
  -0.000123, 
  0.000101, 
  0.000286, 
  0.000383, 
  0.000370, 
  0.000256, 
  0.000077, 
  -0.000114, 
  -0.000264, 
  -0.000333, 
  -0.000308, 
  -0.000199, 
  -0.000041, 
  0.000120, 
  0.000239, 
  0.000286, 
  0.000252, 
  0.000151, 
  0.000014, 
  -0.000119, 
  -0.000212, 
  -0.000242, 
  -0.000203, 
  -0.000111, 
  0.000006, 
  0.000115, 
  0.000185, 
  0.000201, 
  0.000161, 
  0.000079, 
  -0.000020, 
  -0.000107, 
  -0.000159, 
  -0.000164, 
  -0.000125, 
  -0.000053, 
  0.000028, 
  0.000096, 
  0.000134, 
  0.000132, 
  0.000094, 
  0.000034, 
  -0.000032, 
  -0.000084, 
  -0.000110, 
  -0.000104, 
  -0.000070, 
  -0.000019, 
  0.000033, 
  0.000072, 
  0.000088, 
  0.000079, 
  0.000050, 
  0.000009, 
  -0.000031, 
  -0.000059, 
  -0.000069, 
  -0.000059, 
  -0.000034, 
  -0.000002, 
  0.000028, 
  0.000047, 
  0.000052, 
  0.000042, 
  0.000022, 
  -0.000002, 
  -0.000023, 
  -0.000036, 
  -0.000038, 
  -0.000029, 
  -0.000013, 
  0.000004, 
  0.000018, 
  0.000026, 
  0.000026};
#endif
#define I2S_BUFFER_SIZE 1024 * 4 * 2
int16_t  data_i2s[I2S_BUFFER_SIZE];
float32_t mic1_data1[I2S_BUFFER_SIZE / 4], mic1_data2[I2S_BUFFER_SIZE / 4];
volatile int16_t sample_i2s;
volatile uint8_t button_flag, start_stop_recording;
volatile uint8_t  half_i2s, full_i2s;
arm_rfft_fast_instance_f32 fft_audio_instance;



arm_fir_instance_f32 fir_instance;
float32_t fir_state[I2S_BUFFER_SIZE / 4 + FILTER_TAP_NUM - 1];



#define UART_TX_BUFFER_SIZE 512 
static uint32_t uart_tx_buffer[512];
static volatile uint8_t uart_tx_busy = 0;

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_I2S2_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_I2C1_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART2) {
        uart_tx_busy = 0;
    }
}
int compare_peaks(const void* a, const void* b) {
  FrequencyPeak* peak_a = (FrequencyPeak*)a;
  FrequencyPeak* peak_b = (FrequencyPeak*)b;
  if (peak_a->magnitude > peak_b->magnitude) return -1;
  if (peak_a->magnitude < peak_b->magnitude) return 1;
  return 0;
}


void send_top_frequencies(float32_t* fft_data, uint16_t fft_size, uint32_t sample_rate) {
  uint16_t useful_bins = fft_size / 2;
  FrequencyPeak max_peak = {0};
  float32_t max_magnitude = 0;
  uint16_t max_bin = 0;
  
  float32_t freq_resolution = (float32_t)sample_rate / fft_size;
  
  // Find the highest magnitude peak in our frequency range of interest
  for (uint16_t i = 1; i < useful_bins - 1; i++) {
      float32_t frequency = i * freq_resolution;
      if ((frequency > 30.0f) && (frequency < 700.0f)) {
          // Only consider local maxima
          if (fft_data[i] > fft_data[i-1] && fft_data[i] > fft_data[i+1]) {
              if (fft_data[i] > max_magnitude) {
                  max_magnitude = fft_data[i];
                  max_bin = i;
              }
          }
      }
  }
  
  // If we found a peak, perform quadratic interpolation
  if (max_bin > 0) {
      // Get the values of the peak and its neighbors
      float32_t alpha = fft_data[max_bin - 1];
      float32_t beta = fft_data[max_bin];
      float32_t gamma = fft_data[max_bin + 1];
      
      // Calculate the interpolated bin offset
      float32_t p = 0.5f * (alpha - gamma) / (alpha - 2*beta + gamma);
      
      // Calculate interpolated frequency and magnitude
      float32_t interpolated_freq = (max_bin + p) * freq_resolution;
      float32_t interpolated_mag = beta - 0.25f * (alpha - gamma) * p;
      
      // Prepare output string
      char buffer[100];
      
      // Convert float to string with fixed precision
      int freq_int = (int)interpolated_freq;
      int freq_dec = (int)((interpolated_freq - freq_int) * 100); // 2 decimal places
      int mag_int = (int)interpolated_mag;
      int mag_dec = (int)((interpolated_mag - mag_int) * 100);    // 2 decimal places
      
      // Build the output string
      strcpy(buffer, "");
      strcat(buffer, "Freq: ");
      
      // Format frequency with 2 decimal places
      char freq_str[20];
      sprintf(freq_str, "%3d.%02d Hz, ", freq_int, freq_dec);
      strcat(buffer, freq_str);
      
      // Add magnitude
      strcat(buffer, "Mag: ");
      
      // Format magnitude with 2 decimal places
      char mag_str[20];
      sprintf(mag_str, "%3d.%02d\r\n", mag_int, mag_dec);
      strcat(buffer, mag_str);
      
      // Send the output
      send_uart(buffer, strlen(buffer));
  }
  
  // Send final line break
  char *footer = "\r\n";
  send_uart(footer, strlen(footer));
}


// int _write(int file, char *ptr, int len)
// {
//     if (file != STDOUT_FILENO && file != STDERR_FILENO) {
//         errno = EBADF;
//         return -1;
//     }

//     HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, 100);
//     return len;
// }

void send_uart(char *ptr, int len)
{
  HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, 100);
}


// void send_fft_data(float32_t* fft_data, size_t data_size)
// {
//     while (uart_tx_busy) {
//         // Wait for previous transfer to complete
//     }

//     // Copy data directly as it's already 32-bit aligned
//     memcpy(uart_tx_buffer, fft_data, data_size * 4);
    
//     // Ensure the end marker is properly set
//     uart_tx_buffer[data_size-1] = ('>'<<24|'>'<<16|'>'<<8|'>');

//     uart_tx_busy = 1;
//     HAL_UART_Transmit_DMA(&huart2, (uint8_t*)uart_tx_buffer, data_size * 4);
// }



/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */
  uint8_t uart_counter = 0;
  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_I2S2_Init();
  MX_USART2_UART_Init();
  MX_I2C1_Init();
  /* USER CODE BEGIN 2 */
  HAL_I2S_DMAStop(&hi2s2);
  HAL_Delay(500);
  arm_rfft_fast_init_f32(&fft_audio_instance, I2S_BUFFER_SIZE / 4);
  arm_fir_init_f32(&fir_instance, FILTER_TAP_NUM, (float32_t *)h, fir_state, I2S_BUFFER_SIZE / 4);

  char *msg = "Hello World!\r\n";
  send_uart(msg, strlen(msg));

  start_stop_recording = 1;

  msg = "start_recording\r\n";
  send_uart(msg, strlen(msg));
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_12, GPIO_PIN_SET); // Turn on the LED
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_SET); // Turn on the LED
  HAL_Delay(1000);
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_12, GPIO_PIN_RESET); // Turn off the LED
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); // Turn off the LED
  HAL_I2S_Receive_DMA(&hi2s2, (uint16_t *)data_i2s, sizeof(data_i2s)/2);
  HAL_Delay(1000);
  full_i2s = 0;
  half_i2s = 0;
  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
	  HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_4);  // Toggle PB4
	  // HAL_Delay(10);  
        // Delay for 500ms (0.5 seconds)
    // Add LED flashing during recording
    static uint32_t led_timestamp = 0;
    if(start_stop_recording)
    {
        if(HAL_GetTick() - led_timestamp > 500) // Flash every 500ms
        {
            HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_12); // Toggle the LED pin
            led_timestamp = HAL_GetTick();
        }
    }

  }
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 8;
  RCC_OscInitStruct.PLL.PLLN = 168;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 4;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.ClockSpeed = 100000;
  hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief I2S2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2S2_Init(void)
{

  /* USER CODE BEGIN I2S2_Init 0 */

  /* USER CODE END I2S2_Init 0 */

  /* USER CODE BEGIN I2S2_Init 1 */

  /* USER CODE END I2S2_Init 1 */
  hi2s2.Instance = SPI2;
  hi2s2.Init.Mode = I2S_MODE_MASTER_RX;
  hi2s2.Init.Standard = I2S_STANDARD_PHILIPS;
  hi2s2.Init.DataFormat = I2S_DATAFORMAT_16B_EXTENDED;
  hi2s2.Init.MCLKOutput = I2S_MCLKOUTPUT_DISABLE;
  hi2s2.Init.AudioFreq = I2S_AUDIOFREQ_16K;
  hi2s2.Init.CPOL = I2S_CPOL_LOW;
  hi2s2.Init.ClockSource = I2S_CLOCK_PLL;
  hi2s2.Init.FullDuplexMode = I2S_FULLDUPLEXMODE_DISABLE;
  if (HAL_I2S_Init(&hi2s2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2S2_Init 2 */

  /* USER CODE END I2S2_Init 2 */

}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{

  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */

  /* USER CODE END USART2_Init 2 */

}

/**
  * Enable DMA controller clock
  */
static void MX_DMA_Init(void)
{

  /* DMA controller clock enable */
  __HAL_RCC_DMA1_CLK_ENABLE();

  /* DMA interrupt init */
  /* DMA1_Stream3_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Stream3_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Stream3_IRQn);
  /* DMA1_Stream6_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Stream6_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Stream6_IRQn);

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12, GPIO_PIN_RESET);

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET);

  /*Configure GPIO pins : PC10 PC11 PC12 */
  GPIO_InitStruct.Pin = GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

  /*Configure GPIO pin : PB4 */
  GPIO_InitStruct.Pin = GPIO_PIN_4;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */
int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		ITM_SendChar(*ptr++);
	}
	return len;
}
//	l,r,l,r,l,

// RxHalfCpltCallback modification
void HAL_I2S_RxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
{
    static float32_t data_out_fft1[I2S_BUFFER_SIZE / 4];
    static float32_t filtered_data[I2S_BUFFER_SIZE / 4];

    HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_11);
    half_i2s = 1;
    
    // Process the data
    for(int i = 0; i < I2S_BUFFER_SIZE / 4; i++ ) {
        mic1_data1[i] = (float32_t)data_i2s[i * 2];
    }
    
#ifdef FIR_ENABLE
    // Apply FIR filter
    arm_fir_f32(&fir_instance, mic1_data1, filtered_data, I2S_BUFFER_SIZE / 4);
    
    // Apply FFT to filtered data
    arm_rfft_fast_f32(&fft_audio_instance, filtered_data, data_out_fft1, 0);
#else
    // Apply FFT directly to input data
    arm_rfft_fast_f32(&fft_audio_instance, mic1_data1, data_out_fft1, 0);
#endif

    arm_cmplx_mag_f32(data_out_fft1, data_out_fft1, I2S_BUFFER_SIZE / 8);
    data_out_fft1[0] = 0;  // bias removal

    // Send data based on defined tags
#ifdef TAG_TOP_TEN_FREQ
    send_top_frequencies(data_out_fft1, I2S_BUFFER_SIZE / 4, 16000);
#endif

#ifdef TAG_FFT_ALL
    uint8_t start_marker = 0xAA;
    HAL_UART_Transmit(&huart2, &start_marker, 1, 10);
    HAL_UART_Transmit(&huart2, (uint8_t *)data_out_fft1, I2S_BUFFER_SIZE / 8 * sizeof(float32_t), 100);
    uint8_t end_marker = 0x55;
    HAL_UART_Transmit(&huart2, &end_marker, 1, 10);
#endif
}

// RxCpltCallback modification
void HAL_I2S_RxCpltCallback(I2S_HandleTypeDef *hi2s)
{
    static float32_t data_out_fft2[I2S_BUFFER_SIZE / 4];
    static float32_t filtered_data[I2S_BUFFER_SIZE / 4];
    HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_12);
    full_i2s = 1;
    
    for(int i = 0; i < I2S_BUFFER_SIZE / 4; i++ ) {
        mic1_data2[i] = (float32_t)data_i2s[i * 2 + I2S_BUFFER_SIZE / 2];
    }
    
#ifdef FIR_ENABLE
    // Apply FIR filter
    arm_fir_f32(&fir_instance, mic1_data2, filtered_data, I2S_BUFFER_SIZE / 4);
    
    // Apply FFT to filtered data
    arm_rfft_fast_f32(&fft_audio_instance, filtered_data, data_out_fft2, 0);
#else
    // Apply FFT directly to input data
    arm_rfft_fast_f32(&fft_audio_instance, mic1_data2, data_out_fft2, 0);
#endif

    arm_cmplx_mag_f32(data_out_fft2, data_out_fft2, I2S_BUFFER_SIZE / 8);
    data_out_fft2[0] = 0;  // bias removal

    // Send data based on defined tags
#ifdef TAG_TOP_TEN_FREQ
    send_top_frequencies(data_out_fft2, I2S_BUFFER_SIZE / 4, 16000);
#endif

#ifdef TAG_FFT_ALL
    uint8_t start_marker = 0xAA;
    HAL_UART_Transmit(&huart2, &start_marker, 1, 10);
    HAL_UART_Transmit(&huart2, (uint8_t *)data_out_fft2, I2S_BUFFER_SIZE / 8 * sizeof(float32_t), 100);
    uint8_t end_marker = 0x55;
    HAL_UART_Transmit(&huart2, &end_marker, 1, 10);
#endif

    // Restart DMA
    HAL_I2S_Receive_DMA(&hi2s2, (uint16_t *)data_i2s, sizeof(data_i2s)/2);
}

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
